### ISSUE TITLE
 surface = Surface.read_triangular('lh.white') has problem

### ISSUE THREAD

**Issue by tanjia123456** [fphammerle/freesurfer-surface#51]
`
from freesurfer_surface import Surface
surface = Surface.read_triangular('lh.white')
with open('lhedges.txt', "w") as f:
    for triangle in surface.triangles:
        for edge_vertex_indices in triangle.adjacent_vertex_indices():
            edge_vertices = surface.select_vertices(edge_vertex_indices)
            f.write("{} {}\n".format(edge_vertex_indices[0],edge_vertex_indices[1]))
`

Traceback (most recent call last):
  File "D:/my_subject/2020.7.1-7.7/2016GCN/graph-to-spectral-coordinate/fsaverage5/test1.py", line 19, in <module>
    surface = Surface.read_triangular('lh.white')
  File "D:\anaconda3.4\lib\site-packages\freesurfer_surface\__init__.py", line 431, in read_triangular
    surface._read_triangular(surface_file)
  File "D:\anaconda3.4\lib\site-packages\freesurfer_surface\__init__.py", line 424, in _read_triangular
    self.command_lines = list(self._read_cmdlines(stream))
  File "D:\anaconda3.4\lib\site-packages\freesurfer_surface\__init__.py", line 381, in _read_cmdlines
    assert tag == cls._TAG_CMDLINE  # might be TAG_GROUP_AVG_SURFACE_AREA
AssertionError

Is there a problem with the library file?

**Comment by fphammerle** [comment]
Hi @tanjia123456,

I was able to read https://github.com/tanjia123456/Mindboggle_datasets/blob/e09c454d0a07d968bb8531d96f9a2dc8a5f4fe79/lh.white with freesurfer-stats (commit 26bdd6af7e7eb863100974a22450c5f99395cfa8):
```python

In [1]: import freesurfer_surface

In [2]: surface = freesurfer_surface.Surface.read_triangular('lh.white')

In [3]: len(surface.vertices)
Out[3]: 130921

In [4]: surface.creator
Out[4]: b'arno'

In [5]: surface.creation_datetime
Out[5]: datetime.datetime(2012, 8, 17, 9, 39, 26)

In [6]: !sha256sum lh.white
62bfa01abd9669f2baafc81b2adb1a3d833d2df7f2dbdd91bb7f2981a0ece689  lh.white
```

What version of `freesurfer-surface` do you use?

**Comment by tanjia123456** [comment]
> Hi @tanjia123456,
> 
> I was able to read https://github.com/tanjia123456/Mindboggle_datasets/blob/e09c454d0a07d968bb8531d96f9a2dc8a5f4fe79/lh.white with freesurfer-stats (commit [26bdd6a](https://github.com/fphammerle/freesurfer-surface/commit/26bdd6af7e7eb863100974a22450c5f99395cfa8)):
> 
> ```python
> In [1]: import freesurfer_surface
> 
> In [2]: surface = freesurfer_surface.Surface.read_triangular('lh.white')
> 
> In [3]: len(surface.vertices)
> Out[3]: 130921
> 
> In [4]: surface.creator
> Out[4]: b'arno'
> 
> In [5]: surface.creation_datetime
> Out[5]: datetime.datetime(2012, 8, 17, 9, 39, 26)
> 
> In [6]: !sha256sum lh.white
> 62bfa01abd9669f2baafc81b2adb1a3d833d2df7f2dbdd91bb7f2981a0ece689  lh.white
> ```
> 
> What version of `freesurfer-surface` do you use?

2.0.0

**Comment by tanjia123456** [comment]
Hello, I have met another question. when  I use List Labels in Annotation File
`from freesurfer_surface import Annotation

annotation = Annotation.read('**.annot')
for label in annotation.labels.values():
    print(label.index, label.hex_color_code, label.name)
`
the error is:
`D:\installAPP\Anaconda\python.exe D:/MySubject/My_article/Mindboggle/data_label_orig_after/orig/read_annot1.py
Traceback (most recent call last):
  File "D:/MySubject/My_article/Mindboggle/data_label_orig_after/orig/read_annot1.py", line 3, in <module>
    annotation = Annotation.read('subject1.annot')
  File "C:\Users\86177\AppData\Roaming\Python\Python36\site-packages\freesurfer_surface\__init__.py", line 349, in read
    annotation._read(annotation_file)
  File "C:\Users\86177\AppData\Roaming\Python\Python36\site-packages\freesurfer_surface\__init__.py", line 340, in _read
    for vertex_index, color_code in annotations
  File "C:\Users\86177\AppData\Roaming\Python\Python36\site-packages\freesurfer_surface\__init__.py", line 340, in <dictcomp>
    for vertex_index, color_code in annotations
KeyError: 1639705`

**Comment by tanjia123456** [comment]
![image](https://user-images.githubusercontent.com/66013865/141992133-44bf588f-0bae-4ed8-9082-2045eeb86e0e.png)

**Comment by fphammerle** [comment]
Looks like either `*.annot` is corrupt (using color code that was not defined in its header) or freesurfer introduced a breaking change in the file format.

error occurs here:
https://github.com/fphammerle/freesurfer-surface/blob/v2.0.0/freesurfer_surface/__init__.py#L339

**Comment by tanjia123456** [comment]
> 

Thanks, I found a project called nibabel that seems to achieve what I want.
https://github.com/nipy/nibabel

**Comment by fphammerle** [comment]
Ah great, I haven't heard of that project yet, thanks!
